version: '3.8'

services:
 mongo:
  image: mongo:latest
  container_name: mongodb
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_DATABASE: NodeJSAssessment

 app:
  build: .
  container_name: amir-ghodi-answersai-backend
  ports:
    - "3000:3000"
  environment:
    - MONGO_URI=mongodb://host.docker.internal:27017/NodeJSAssessment
    - JWT_SECRET=JWT_SECRET
    - OPENAI_API_KEY=OPENAI_API_KEY
    - PORT=3000
  depends_on:
    - mongo
